// Wacawaci: 7 locker -> Video/Modul, mapped from the configured Google Drive root.
import type { VercelRequest,VercelResponse } from '@vercel/node';
import crypto from 'node:crypto';
import {supabaseConfigured,supabaseRequest} from '../_lib/supabase';
import {validMentorCode} from '../_lib/mentorBank';

type Resource={id:string;kind:string;title:string;description:string;url:string;is_public:boolean;created_by:string;level:string;subtest:string;created_at?:string};
const validLevels=['nguli','mandor','supervisor'];
const validKinds=['video','module','ringkasan','cheatsheet'];
const validSubtests=['pu','ppu','pbm','pk','lit_indo','lit_inggris','pm'];
const DRIVE_ROOT_ID='1hUF0G01PZkzRcONhLFRAywGi_qD8AUds';
const DRIVE_API='https://www.googleapis.com/drive/v3/files';
const memoryResources:Resource[]=[];
function mentorCodeFrom(req:any,body?:any){return String(req.query?.mentor_code||body?.mentor_code||body?.code||'').trim().toUpperCase()}
function normalize(value:string){return value.toLowerCase().replace(/[_()\-]+/g,' ').replace(/\s+/g,' ').trim()}
function inferSubtest(path:string){const p=normalize(path).replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();if(/literasi bahasa indonesia|literasi indonesia|(^| )lit indo( |$)/.test(p))return'lit_indo';if(/literasi bahasa inggris|literasi inggris|(^| )lit inggris( |$)/.test(p))return'lit_inggris';if(/pengetahuan .*pemahaman umum|(^| )ppu( |$)/.test(p))return'ppu';if(/pemahaman bacaan|pemahaman .*menulis|(^| )pbm( |$)/.test(p))return'pbm';if(/pengetahuan kuantitatif|(^| )pk( |$)/.test(p))return'pk';if(/penalaran matematika|(^| )pm( |$)/.test(p))return'pm';if(/penalaran umum|(^| )pu( |$)/.test(p))return'pu';return null}
function inferKind(path:string,mimeType:string){const p=normalize(path);if(/video|vidio/.test(p)||mimeType.startsWith('video/'))return'video';if(/modul|module|materi|pdf|document|docs/.test(p)||mimeType==='application/pdf'||mimeType.includes('document'))return'module';return null}
function parse(row:any):Resource|null{try{const d=typeof row?.description==='string'?JSON.parse(row.description):row?.data;if(d?.subtest)return d as Resource;return {id:String(row.id),kind:String(row.kind||'module'),title:String(row.title||''),description:String(row.description||''),url:String(row.url||''),is_public:Boolean(row.is_public),created_by:String(row.created_by||''),level:String(row.level||'nguli'),subtest:'pu',created_at:row.created_at}}catch{return null}}
async function driveList(params:Record<string,string>){const key=String(process.env.GOOGLE_DRIVE_API_KEY||'').trim();if(!key)return[];const all:any[]=[];let pageToken='';do{const queryParams=new URLSearchParams({...params,pageSize:'100',...(pageToken?{pageToken}:{}),key});const response=await fetch(`${DRIVE_API}?${queryParams.toString()}`);const text=await response.text();if(!response.ok)throw new Error(`Google Drive API gagal (${response.status}): ${text.slice(0,300)}`);const body=JSON.parse(text);if(Array.isArray(body.files))all.push(...body.files);pageToken=String(body.nextPageToken||'')}while(pageToken);return all}
async function driveResources():Promise<Resource[]>{const key=String(process.env.GOOGLE_DRIVE_API_KEY||'').trim();if(!key)return[];const result:Resource[]=[];const seen=new Set<string>();const queue:Array<{id:string;path:string}>=[{id:DRIVE_ROOT_ID,path:''}];while(queue.length){const current=queue.shift()!;if(seen.has(current.id))continue;seen.add(current.id);const children=await driveList({q:`'${current.id}' in parents and trashed = false`,fields:'nextPageToken,files(id,name,mimeType,webViewLink,parents)'});for(const item of children){const itemPath=current.path?`${current.path}/${item.name}`:item.name;if(item.mimeType==='application/vnd.google-apps.folder'){queue.push({id:item.id,path:itemPath});continue}const subtest=inferSubtest(itemPath),kind=inferKind(itemPath,String(item.mimeType||''));if(!subtest||!kind)continue;result.push({id:`drive-${item.id}`,kind,title:item.name,description:itemPath,url:item.webViewLink||`https://drive.google.com/open?id=${item.id}`,is_public:true,created_by:'Google Drive Wacawaci',level:'',subtest})}}return result}
export default async function handler(req:VercelRequest,res:VercelResponse){try{
 if(req.method==='GET'){
  const db:Resource[]=[];if(supabaseConfigured()){try{const rows=await supabaseRequest<any[]>('wacawaci_resources?kind=not.in.(mentor_question,mentor_tryout,live_class)&select=*&order=created_at.desc');db.push(...rows.map(parse).filter(Boolean) as Resource[])}catch(e){console.error('WACAWACI_DB_LOAD_ERROR',e)}}
  let drive:Resource[]=[];try{drive=await driveResources()}catch(e){console.error('WACAWACI_DRIVE_LOAD_ERROR',e)}const seen=new Set(db.map(x=>x.id));return res.status(200).json([...db,...drive,...memoryResources.filter(x=>!seen.has(x.id))]);
 }
 if(req.method==='DELETE'){if(!validMentorCode(mentorCodeFrom(req)))return res.status(401).json({detail:'Kode mentor tidak cocok.'});const id=String(req.query?.id||req.body?.id||'').trim();if(supabaseConfigured())try{await supabaseRequest(`wacawaci_resources?id=eq.${encodeURIComponent(id)}`,{method:'DELETE'})}catch(e){console.error('WACAWACI_DELETE_ERROR',e)}const index=memoryResources.findIndex(x=>x.id===id);if(index>=0)memoryResources.splice(index,1);return res.status(200).json({ok:true,id})}
 if(req.method!=='POST')return res.status(405).json({detail:'Method tidak didukung.'});
 let body:any=req.body||{};if(typeof body==='string'){try{body=JSON.parse(body||'{}')}catch{body={}}}if(!validMentorCode(mentorCodeFrom(req,body)))return res.status(401).json({detail:'Kode mentor tidak cocok.'});
 const level=validLevels.includes(body.level)?body.level:'nguli',kind=validKinds.includes(body.kind)?body.kind:'module',subtest=validSubtests.includes(body.subtest)?body.subtest:'pu',title=String(body.title||'').trim(),description=String(body.description||'').trim(),url=String(body.url||body.file_url||body.video_url||'').trim();if(!title)return res.status(400).json({detail:'Judul materi wajib diisi.'});if(!url)return res.status(400).json({detail:'Masukkan link Google Drive/YouTube.'});
 const resource:Resource={id:`res-${Date.now()}-${crypto.randomBytes(3).toString('hex')}`,kind,title,description,url,is_public:true,created_by:'Mentor Malas Belajar',level,subtest,created_at:new Date().toISOString()};
 if(supabaseConfigured())await supabaseRequest('wacawaci_resources',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({id:resource.id,kind:resource.kind,title:resource.title,description:JSON.stringify(resource),url:resource.url,is_public:true,created_by:resource.created_by,level:resource.level,created_at:resource.created_at})});else memoryResources.unshift(resource);
 return res.status(201).json(resource);
 }catch(e){console.error('WACAWACI_API_ERROR',e);return res.status(500).json({detail:e instanceof Error?e.message:'Gagal memproses Wacawaci.'})}}
